<a href="https://colab.research.google.com/github/Karthika239/Learning/blob/main/Movie_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PROJECT 1

Data Analysis on Movie Dataset

In [42]:
# Supress Warnings

import warnings
warnings.filterwarnings('ignore')

# Import the numpy and pandas packages

import numpy as np
import pandas as pd

In [6]:
#Read Dataset
movies = pd.read_csv('/content/Movie_Data.csv')
display(movies.head())

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [7]:
#inspect data
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5022 non-null   float64
 19  language                   5029 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [9]:
movies.shape

(5043, 28)

In [10]:
movies.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [11]:
movies.dtypes

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

In [ ]:
# inspect null values

In [13]:
#Column-wise null count
movies.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      14
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [14]:
#Row-wise null count :
movies.isnull().sum(axis=1)

0        0
1        0
2        0
3        0
4       14
        ..
5038     4
5039     5
5040     4
5041     2
5042     0
Length: 5043, dtype: int64

In [15]:
#Column-wise null percentages:

round(movies.isnull().sum() / len(movies) * 100, 2)

color                         0.38
director_name                 2.06
num_critic_for_reviews        0.99
duration                      0.30
director_facebook_likes       2.06
actor_3_facebook_likes        0.46
actor_2_name                  0.26
actor_1_facebook_likes        0.14
gross                        17.53
genres                        0.00
actor_1_name                  0.14
movie_title                   0.00
num_voted_users               0.00
cast_total_facebook_likes     0.00
actor_3_name                  0.46
facenumber_in_poster          0.26
plot_keywords                 3.03
movie_imdb_link               0.00
num_user_for_reviews          0.42
language                      0.28
country                       0.10
content_rating                6.01
budget                        9.76
title_year                    2.14
actor_2_facebook_likes        0.26
imdb_score                    0.00
aspect_ratio                  6.52
movie_facebook_likes          0.00
dtype: float64

How it works:

isnull() — returns a DataFrame of True/False for each value

.sum() — counts True values (column-wise by default)

.sum(axis=1) — counts across columns (row-wise)

/ len(movies) * 100 — converts count to percentage

round(..., 2) — rounds to 2 decimal places

In [16]:
#Drop unnecessary columns
columns_to_drop = [
    'color', 'director_facebook_likes', 'actor_1_facebook_likes',
    'actor_2_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
    'cast_total_facebook_likes', 'actor_3_name', 'duration',
    'facenumber_in_poster', 'content_rating', 'country',
    'movie_imdb_link', 'aspect_ratio', 'plot_keywords'
]

movies = movies.drop(columns=columns_to_drop)

In [17]:
movies.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
4,Doug Walker,NaN,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,NaN,NaN,NaN,NaN,7.1,0

How it works:

drop(columns=...) — removes the listed columns

movies = movies.drop(...) — reassigns so the change is saved back to movies

movies.head() — lets you inspect the result to confirm columns are gone

In [18]:
#Drop rows where columns have >5% null values:
null_percent = round(movies.isnull().sum() / len(movies) * 100, 2)
high_null_cols = null_percent[null_percent > 5].index

In [19]:
movies = movies.dropna(subset=high_null_cols)

In [20]:
movies.shape

(3891, 13)

How it works:

null_percent — reuses the percentage calculation from subtask 2.1

null_percent > 5 — filters to only columns where nulls exceed 5%

.index — extracts just the column names

dropna(subset=high_null_cols) — drops any row that has a NaN in any of those high-null columns

movies.shape — lets you verify how many rows remain after dropping

In [21]:
#drop unnecessary rows
movies = movies[movies.isnull().sum(axis=1) <= 5]
movies.shape

(3891, 13)

In [22]:
#Fill NaN values in the language column with 'English'
movies['language'].fillna('English', inplace=True)
movies['language'].isnull().sum()

np.int64(0)

How it works

fillna('English') — replaces all NaN values in the language column with 'English'

inplace=True — modifies the dataframe directly without needing to reassign

.isnull().sum() — confirms the result should be 0 (no nulls left)

Perform Data Analysis on this Clean data:

In [23]:
#Change unit of columns
#Convert budget and gross from $ to million $:

movies['budget'] = movies['budget'] / 1000000
movies['gross'] = movies['gross'] / 1000000

movies[['budget', 'gross']].head()

   budget       gross
0   237.0  760.505847
1   300.0  309.404152
2   245.0  200.074175
3   250.0  448.130642
5   263.7   73.058679

How it works:

Dividing by 1000000 converts the values from dollars to million dollars

movies[['budget', 'gross']].head() — inspect both columns to confirm the conversion worked

In [24]:
#Movies with highest Profit:
#Create the profit column:
movies['profit'] = movies['gross'] - movies['budget']
movies.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.505847
1,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300.0,2007.0,7.1,0,9.404152
2,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245.0,2015.0,6.8,85000,-44.925825
3,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250.0,2012.0,8.5,164000,198.130642
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.7,2012.0,6.6,24000,-190.641321

In [25]:
#Sort the dataframe by profit:
movies = movies.sort_values('profit', ascending=False)
movies.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.5,1982.0,7.9,34000,424.449459

In [26]:
#Extract top 10 profiting movies:
top10 = movies.head(10)
top10[['movie_title', 'director_name', 'budget', 'gross', 'profit']]

,movie_title,director_name,budget,gross,profit
0,Avatar,James Cameron,237.0,760.505847,523.505847
29,Jurassic World,Colin Trevorrow,150.0,652.177271,502.177271
26,Titanic,James Cameron,200.0,658.672302,458.672302
3024,Star Wars: Episode IV - A New Hope,George Lucas,11.0,460.935665,449.935665
3080,E.T. the Extra-Terrestrial,Steven Spielberg,10.5,434.949459,424.449459
17,The Avengers,Joss Whedon,220.0,623.279547,403.279547
794,The Avengers,Joss Whedon,220.0,623.279547,403.279547
509,The Lion King,Roger Allers,45.0,422.783777,377.783777
240,Star Wars: Episode I - The Phantom Menace,George Lucas,115.0,474.544677,359.544677
66,The Dark Knight,Christopher Nolan,185.0,533.316061,348.316061

How it works:

gross - budget — profit is simply revenue minus cost

sort_values('profit', ascending=False) — sorts in descending order (highest profit first)

movies.head(10) — extracts the top 10 rows after sorting

In [27]:
#drop duplicates
movies = movies.drop_duplicates()
movies.shape

(3856, 14)

In [28]:
#recalculate:
movies['profit'] = movies['gross'] - movies['budget']
movies = movies.sort_values('profit', ascending=False)

top10 = movies.head(10)
top10[['movie_title', 'director_name', 'budget', 'gross', 'profit']]

,movie_title,director_name,budget,gross,profit
0,Avatar,James Cameron,237.0,760.505847,523.505847
29,Jurassic World,Colin Trevorrow,150.0,652.177271,502.177271
26,Titanic,James Cameron,200.0,658.672302,458.672302
3024,Star Wars: Episode IV - A New Hope,George Lucas,11.0,460.935665,449.935665
3080,E.T. the Extra-Terrestrial,Steven Spielberg,10.5,434.949459,424.449459
17,The Avengers,Joss Whedon,220.0,623.279547,403.279547
509,The Lion King,Roger Allers,45.0,422.783777,377.783777
240,Star Wars: Episode I - The Phantom Menace,George Lucas,115.0,474.544677,359.544677
66,The Dark Knight,Christopher Nolan,185.0,533.316061,348.316061
439,The Hunger Games,Gary Ross,78.0,407.999255,329.999255

How it works:

drop_duplicates() — removes all duplicate rows from the dataframe

After dropping duplicates, we redo the profit calculation and sorting to get a clean top 10

In [29]:
# TOP 250 movies
IMDb_Top_250 = movies[movies['num_voted_users'] > 25000].sort_values('imdb_score', ascending=False).head(250)

In [30]:
IMDb_Top_250['Rank'] = range(1, 251)

IMDb_Top_250[['Rank', 'movie_title', 'director_name', 'imdb_score', 'num_voted_users']]

,Rank,movie_title,director_name,imdb_score,num_voted_users
1937,1,The Shawshank Redemption,Frank Darabont,9.3,1689764
3466,2,The Godfather,Francis Ford Coppola,9.2,1155770
2837,3,The Godfather: Part II,Francis Ford Coppola,9.0,790926
66,4,The Dark Knight,Christopher Nolan,9.0,1676169
3355,5,Pulp Fiction,Quentin Tarantino,8.9,1324680
...,...,...,...,...,...
1606,246,The Notebook,Nick Cassavetes,7.9,396396
2177,247,Edward Scissorhands,Tim Burton,7.9,357581
1735,248,Walk the Line,James Mangold,7.9,188637
1884,249,The Untouchables,Brian De Palma,7.9,219008
3361,250,Little Miss Sunshine,Jonathan Dayton,7.9,355810

In [ ]:
# Extract top foreign language films:

In [31]:
Top_Foreign_Lang_Film = IMDb_Top_250[IMDb_Top_250['language'] != 'English']
Top_Foreign_Lang_Film[['Rank', 'movie_title', 'director_name', 'language', 'imdb_score']]

,Rank,movie_title,director_name,language,imdb_score
4498,8,"The Good, the Bad and the Ugly",Sergio Leone,Italian,8.9
4747,15,Seven Samurai,Akira Kurosawa,Japanese,8.7
4029,19,City of God,Fernando Meirelles,Portuguese,8.7
2373,22,Spirited Away,Hayao Miyazaki,Japanese,8.6
4921,29,Children of Heaven,Majid Majidi,Persian,8.5
4259,37,The Lives of Others,Florian Henckel von Donnersmarck,German,8.5
2323,47,Princess Mononoke,Hayao Miyazaki,Japanese,8.4
4105,48,Oldboy,Chan-wook Park,Korean,8.4
4659,49,A Separation,Asghar Farhadi,Persian,8.4
2970,55,Das Boot,Wolfgang Petersen,German,8.4
1298,57,Amélie,Jean-Pierre Jeunet,French,8.4
1329,60,Baahubali: The Beginning,S.S. Rajamouli,Telugu,8.4
4033,70,The Hunt,Thomas Vinterberg,Danish,8.3
2734,77,Metropolis,Fritz Lang,German,8.3
2829,82,Downfall,Oliver Hirschbiegel,German,8.3
2047,91,Howl's Moving Castle,Hayao Miyazaki,Japanese,8.2
2551,92,Pan's Labyrinth,Guillermo del Toro,Spanish,8.2
3550,97,Incendies,Denis Villeneuve,French,8.2
4000,106,The Secret in Their Eyes,Juan José Campanella,Spanish,8.2
3553,110,Elite Squad,José Padilha,Portuguese,8.1
4461,122,The Celebration,Thomas Vinterberg,Danish,8.1
2914,124,Tae Guk Gi: The Brotherhood of War,Je-kyu Kang,Korean,8.1
3423,130,Akira,Katsuhiro Ôtomo,Japanese,8.1
4267,137,Amores Perros,Alejandro G. Iñárritu,Spanish,8.1
2830,138,The Sea Inside,Alejandro Amenábar,Spanish,8.1
4284,167,Waltz with Bashir,Ari Folman,Hebrew,8.0
3456,177,Persepolis,Vincent Paronnaud,French,8.0
4144,183,Central Station,Walter Salles,Portuguese,8.0
3344,187,My Name Is Khan,Karan Johar,Hindi,8.0
4897,201,A Fistful of Dollars,Sergio Leone,Italian,8.0
4415,206,Nine Queens,Fabián Bielinsky,Spanish,7.9
3510,210,Veer-Zaara,Yash Chopra,Hindi,7.9
4640,220,"4 Months, 3 Weeks and 2 Days",Cristian Mungiu,Romanian,7.9
2863,222,Letters from Iwo Jima,Clint Eastwood,Japanese,7.9
2605,225,"Crouching Tiger, Hidden Dragon",Ang Lee,Mandarin,7.9
3677,237,The Chorus,Christophe Barratier,French,7.9
3264,238,Amour,Michael Haneke,French,7.9
1171,240,Hero,Yimou Zhang,Mandarin,7.9

How it works:

num_voted_users > 25000 — filters out movies with too few votes (ensures credibility)

sort_values('imdb_score', ascending=False) — highest rated first

.head(250) — keeps only top 250
range(1, 251) — assigns ranks 1 to 250

language != 'English' — filters to only non-English movies

In [32]:
#Extract top 10 directors by mean IMDb score:
top10director = movies.groupby('director_name')['imdb_score'].mean().sort_values(ascending=False).head(10).reset_index()

top10director.columns = ['director_name', 'mean_imdb_score']
top10director

       director_name  mean_imdb_score
0          Tony Kaye         8.600000
1    Charles Chaplin         8.600000
2         Ron Fricke         8.500000
3   Alfred Hitchcock         8.500000
4       Majid Majidi         8.500000
5    Damien Chazelle         8.500000
6       Sergio Leone         8.433333
7  Christopher Nolan         8.425000
8   Richard Marquand         8.400000
9     S.S. Rajamouli         8.400000

How it works:

groupby('director_name') — groups all movies by director

['imdb_score'].mean() — calculates the mean IMDb score for each director

sort_values(ascending=False) — sorts highest mean score first

.head(10) — keeps only top 10

reset_index() — converts the result back to a clean dataframe
.columns — renames columns for clarity

In [33]:
# find popular genre
movies['genre_1'] = movies['genres'].apply(lambda x: x.split('|')[0])
movies['genre_2'] = movies['genres'].apply(lambda x: x.split('|')[1] if len(x.split('|')) > 1 else x.split('|')[0])

movies[['movie_title', 'genres', 'genre_1', 'genre_2']].head()

,movie_title,genres,genre_1,genre_2
0,Avatar,Action|Adventure|Fantasy|Sci-Fi,Action,Adventure
29,Jurassic World,Action|Adventure|Sci-Fi|Thriller,Action,Adventure
26,Titanic,Drama|Romance,Drama,Romance
3024,Star Wars: Episode IV - A New Hope,Action|Adventure|Fantasy|Sci-Fi,Action,Adventure
3080,E.T. the Extra-Terrestrial,Family|Sci-Fi,Family,Sci-Fi

In [34]:
#Group the dataframe:
movies_by_segment = movies.groupby(['genre_1', 'genre_2'])

In [35]:
#5 most popular genre
PopGenre = movies_by_segment['gross'].mean().sort_values(ascending=False).head(5).reset_index()

PopGenre.columns = ['genre_1', 'genre_2', 'mean_gross']
PopGenre

     genre_1    genre_2  mean_gross
0     Family     Sci-Fi  434.949459
1  Adventure     Sci-Fi  228.627758
2  Adventure     Family  118.919540
3  Adventure  Animation  116.998550
4     Action  Adventure  109.595465

In [36]:
#find critic favourite and audience favourite actors
Meryl_Streep = movies[movies['actor_1_name'] == 'Meryl Streep']
Meryl_Streep

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
1408,David Frankel,208.0,124.732962,Comedy|Drama|Romance,Meryl Streep,The Devil Wears Prada,286178,631.0,English,35.0,2006.0,6.8,0,89.732962,Comedy,Drama
1575,Sydney Pollack,66.0,87.100000,Biography|Drama|Romance,Meryl Streep,Out of Africa,52339,200.0,English,31.0,1985.0,7.2,0,56.100000,Biography,Drama
1204,Nora Ephron,252.0,94.125426,Biography|Drama|Romance,Meryl Streep,Julie & Julia,79264,277.0,English,40.0,2009.0,7.0,13000,54.125426,Biography,Drama
1618,David Frankel,234.0,63.536011,Comedy|Drama|Romance,Meryl Streep,Hope Springs,34258,178.0,English,30.0,2012.0,6.3,0,33.536011,Comedy,Drama
410,Nancy Meyers,187.0,112.703470,Comedy|Drama|Romance,Meryl Streep,It's Complicated,69860,214.0,English,85.0,2009.0,6.6,0,27.703470,Comedy,Drama
2781,Phyllida Lloyd,331.0,29.959436,Biography|Drama|History,Meryl Streep,The Iron Lady,82327,350.0,English,13.0,2011.0,6.4,18000,16.959436,Biography,Drama
1925,Stephen Daldry,174.0,41.597830,Drama|Romance,Meryl Streep,The Hours,102123,660.0,English,25.0,2002.0,7.6,0,16.597830,Drama,Romance
3135,Robert Altman,211.0,20.338609,Comedy|Drama|Music,Meryl Streep,A Prairie Home Companion,19655,280.0,English,10.0,2006.0,6.8,683,10.338609,Comedy,Drama
1106,Curtis Hanson,42.0,46.815748,Action|Adventure|Crime|Thriller,Meryl Streep,The River Wild,32544,69.0,English,45.0,1994.0,6.3,0,1.815748,Action,Adventure
1674,Carl Franklin,64.0,23.209440,Drama,Meryl Streep,One True Thing,9283,112.0,English,30.0,1998.0,7.0,592,-6.790560,Drama,Drama
1483,Robert Redford,227.0,14.998070,Drama|Thriller|War,Meryl Streep,Lions for Lambs,41170,298.0,English,35.0,2007.0,6.2,0,-20.001930,Drama,Thriller

In [37]:
Leo_Caprio = movies[movies['actor_1_name'] == 'Leonardo DiCaprio']
Leo_Caprio

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302,Drama,Romance
97,Christopher Nolan,642.0,292.568851,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,160.0,2010.0,8.8,175000,132.568851,Action,Adventure
911,Steven Spielberg,194.0,164.435221,Biography|Crime|Drama,Leonardo DiCaprio,Catch Me If You Can,525801,667.0,English,52.0,2002.0,8.0,15000,112.435221,Biography,Crime
296,Quentin Tarantino,765.0,162.804648,Drama|Western,Leonardo DiCaprio,Django Unchained,955174,1193.0,English,100.0,2012.0,8.5,199000,62.804648,Drama,Western
179,Alejandro G. Iñárritu,556.0,183.635922,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020,1188.0,English,135.0,2015.0,8.1,190000,48.635922,Adventure,Drama
452,Martin Scorsese,490.0,127.968405,Mystery|Thriller,Leonardo DiCaprio,Shutter Island,786092,964.0,English,80.0,2010.0,8.1,53000,47.968405,Mystery,Thriller
361,Martin Scorsese,352.0,132.373442,Crime|Drama|Thriller,Leonardo DiCaprio,The Departed,873649,2054.0,English,90.0,2006.0,8.5,29000,42.373442,Crime,Drama
3476,Baz Luhrmann,490.0,144.812796,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362933,753.0,English,105.0,2013.0,7.3,115000,39.812796,Drama,Romance
50,Baz Luhrmann,490.0,144.812796,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362912,753.0,English,105.0,2013.0,7.3,115000,39.812796,Drama,Romance
2757,Baz Luhrmann,106.0,46.338728,Drama|Romance,Leonardo DiCaprio,Romeo + Juliet,167750,506.0,English,14.5,1996.0,6.8,10000,31.838728,Drama,Romance
1422,Randall Wallace,83.0,56.876365,Action|Adventure,Leonardo DiCaprio,The Man in the Iron Mask,125219,244.0,English,35.0,1998.0,6.4,0,21.876365,Action,Adventure
308,Martin Scorsese,606.0,116.866727,Biography|Comedy|Crime|Drama,Leonardo DiCaprio,The Wolf of Wall Street,780588,1138.0,English,100.0,2013.0,8.2,138000,16.866727,Biography,Comedy
1453,Clint Eastwood,392.0,37.304950,Biography|Crime|Drama,Leonardo DiCaprio,J. Edgar,102728,279.0,English,35.0,2011.0,6.6,16000,2.304950,Biography,Crime
257,Martin Scorsese,267.0,102.608827,Biography|Drama,Leonardo DiCaprio,The Aviator,264318,799.0,English,110.0,2004.0,7.5,0,-7.391173,Biography,Drama
2067,Jerry Zaks,45.0,12.782508,Drama,Leonardo DiCaprio,Marvin's Room,20163,71.0,English,23.0,1996.0,6.7,1000,-10.217492,Drama,Drama
990,Danny Boyle,118.0,39.778599,Adventure|Drama|Thriller,Leonardo DiCaprio,The Beach,176169,548.0,English,50.0,2000.0,6.6,0,-10.221401,Adventure,Drama
1114,Sam Mendes,323.0,22.877808,Drama|Romance,Leonardo DiCaprio,Revolutionary Road,152591,414.0,English,35.0,2008.0,7.3,0,-12.122192,Drama,Romance
1560,Sam Raimi,63.0,18.636537,Action|Thriller|Western,Leonardo DiCaprio,The Quick and the Dead,69197,216.0,English,32.0,1995.0,6.4,0,-13.363463,Action,Thriller
326,Martin Scorsese,233.0,77.679638,Crime|Drama,Leonardo DiCaprio,Gangs of New York,314033,1166.0,English,100.0,2002.0,7.5,0,-22.320362,Crime,Drama
641,Ridley Scott,238.0,39.380442,Action|Drama|Thriller,Leonardo DiCaprio,Body of Lies,174248,263.0,English,70.0,2008.0,7.1,0,-30.619558,Action,Drama
307,Edward Zwick,166.0,57.366262,Adventure|Drama|Thriller,Leonardo DiCaprio,Blood Diamond,400292,657.0,English,100.0,2006.0,8.0,14000,-42.633738,Adventure,Drama

In [38]:
Brad_Pitt = movies[movies['actor_1_name'] == 'Brad Pitt']
Brad_Pitt

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
400,Steven Soderbergh,186.0,183.405771,Crime|Thriller,Brad Pitt,Ocean's Eleven,402645,845.0,English,85.0,2001.0,7.8,0,98.405771,Crime,Thriller
255,Doug Liman,233.0,186.336103,Action|Comedy|Crime|Romance|Thriller,Brad Pitt,Mr. & Mrs. Smith,348861,798.0,English,120.0,2005.0,6.5,0,66.336103,Action,Comedy
940,Neil Jordan,120.0,105.264608,Drama|Fantasy|Horror,Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406.0,English,60.0,1994.0,7.6,11000,45.264608,Drama,Fantasy
470,David Ayer,406.0,85.707116,Action|Drama|War,Brad Pitt,Fury,303185,701.0,English,68.0,2014.0,7.6,82000,17.707116,Action,Drama
254,Steven Soderbergh,198.0,125.531634,Crime|Thriller,Brad Pitt,Ocean's Twelve,284852,627.0,English,110.0,2004.0,6.4,0,15.531634,Crime,Thriller
2204,Alejandro G. Iñárritu,285.0,34.300771,Drama,Brad Pitt,Babel,243799,908.0,English,25.0,2006.0,7.5,0,9.300771,Drama,Drama
2682,Andrew Dominik,414.0,14.938570,Crime|Thriller,Brad Pitt,Killing Them Softly,111625,369.0,English,15.0,2012.0,6.2,20000,-0.061430,Crime,Thriller
2898,Tony Scott,122.0,12.281500,Action|Crime|Drama|Romance|Thriller,Brad Pitt,True Romance,163492,460.0,English,13.0,1993.0,8.0,15000,-0.718500,Action,Crime
2333,Angelina Jolie Pitt,131.0,0.531009,Drama|Romance,Brad Pitt,By the Sea,7976,61.0,English,10.0,2015.0,5.3,0,-9.468991,Drama,Romance
1490,Terrence Malick,584.0,13.303319,Drama|Fantasy,Brad Pitt,The Tree of Life,136367,975.0,English,32.0,2011.0,6.7,39000,-18.696681,Drama,Fantasy
101,David Fincher,362.0,127.490802,Drama|Fantasy|Romance,Brad Pitt,The Curious Case of Benjamin Button,459346,822.0,English,150.0,2008.0,7.8,23000,-22.509198,Drama,Fantasy
683,David Fincher,315.0,37.023395,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,63.0,1999.0,8.8,48000,-25.976605,Drama,Drama
1722,Andrew Dominik,273.0,3.904982,Biography|Crime|Drama|History|Western,Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415.0,English,30.0,2007.0,7.5,0,-26.095018,Biography,Crime
611,Jean-Jacques Annaud,76.0,37.901509,Adventure|Biography|Drama|History|War,Brad Pitt,Seven Years in Tibet,96385,119.0,English,70.0,1997.0,7.0,0,-32.098491,Adventure,Biography
792,Patrick Gilmore,98.0,26.288320,Adventure|Animation|Comedy|Drama|Family|Fantas...,Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91.0,English,60.0,2003.0,6.7,880,-33.711680,Adventure,Animation
147,Wolfgang Petersen,220.0,133.228348,Adventure,Brad Pitt,Troy,381672,1694.0,English,175.0,2004.0,7.2,0,-41.771652,Adventure,Adventure
382,Tony Scott,142.0,0.026871,Action|Crime|Thriller,Brad Pitt,Spy Game,121259,361.0,English,92.0,2001.0,7.0,0,-91.973129,Action,Crime

In [39]:
Combined = pd.concat([Meryl_Streep, Leo_Caprio, Brad_Pitt])
Combined

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
1408,David Frankel,208.0,124.732962,Comedy|Drama|Romance,Meryl Streep,The Devil Wears Prada,286178,631.0,English,35.0,2006.0,6.8,0,89.732962,Comedy,Drama
1575,Sydney Pollack,66.0,87.100000,Biography|Drama|Romance,Meryl Streep,Out of Africa,52339,200.0,English,31.0,1985.0,7.2,0,56.100000,Biography,Drama
1204,Nora Ephron,252.0,94.125426,Biography|Drama|Romance,Meryl Streep,Julie & Julia,79264,277.0,English,40.0,2009.0,7.0,13000,54.125426,Biography,Drama
1618,David Frankel,234.0,63.536011,Comedy|Drama|Romance,Meryl Streep,Hope Springs,34258,178.0,English,30.0,2012.0,6.3,0,33.536011,Comedy,Drama
410,Nancy Meyers,187.0,112.703470,Comedy|Drama|Romance,Meryl Streep,It's Complicated,69860,214.0,English,85.0,2009.0,6.6,0,27.703470,Comedy,Drama
2781,Phyllida Lloyd,331.0,29.959436,Biography|Drama|History,Meryl Streep,The Iron Lady,82327,350.0,English,13.0,2011.0,6.4,18000,16.959436,Biography,Drama
1925,Stephen Daldry,174.0,41.597830,Drama|Romance,Meryl Streep,The Hours,102123,660.0,English,25.0,2002.0,7.6,0,16.597830,Drama,Romance
3135,Robert Altman,211.0,20.338609,Comedy|Drama|Music,Meryl Streep,A Prairie Home Companion,19655,280.0,English,10.0,2006.0,6.8,683,10.338609,Comedy,Drama
1106,Curtis Hanson,42.0,46.815748,Action|Adventure|Crime|Thriller,Meryl Streep,The River Wild,32544,69.0,English,45.0,1994.0,6.3,0,1.815748,Action,Adventure
1674,Carl Franklin,64.0,23.209440,Drama,Meryl Streep,One True Thing,9283,112.0,English,30.0,1998.0,7.0,592,-6.790560,Drama,Drama
1483,Robert Redford,227.0,14.998070,Drama|Thriller|War,Meryl Streep,Lions for Lambs,41170,298.0,English,35.0,2007.0,6.2,0,-20.001930,Drama,Thriller
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302,Drama,Romance
97,Christopher Nolan,642.0,292.568851,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,160.0,2010.0,8.8,175000,132.568851,Action,Adventure
911,Steven Spielberg,194.0,164.435221,Biography|Crime|Drama,Leonardo DiCaprio,Catch Me If You Can,525801,667.0,English,52.0,2002.0,8.0,15000,112.435221,Biography,Crime
296,Quentin Tarantino,765.0,162.804648,Drama|Western,Leonardo DiCaprio,Django Unchained,955174,1193.0,English,100.0,2012.0,8.5,199000,62.804648,Drama,Western
179,Alejandro G. Iñárritu,556.0,183.635922,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020,1188.0,English,135.0,2015.0,8.1,190000,48.635922,Adventure,Drama
452,Martin Scorsese,490.0,127.968405,Mystery|Thriller,Leonardo DiCaprio,Shutter Island,786092,964.0,English,80.0,2010.0,8.1,53000,47.968405,Mystery,Thriller
361,Martin Scorsese,352.0,132.373442,Crime|Drama|Thriller,Leonardo DiCaprio,The Departed,873649,2054.0,English,90.0,2006.0,8.5,29000,42.373442,Crime,Drama
3476,Baz Luhrmann,490.0,144.812796,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362933,753.0,English,105.0,2013.0,7.3,115000,39.812796,Drama,Romance
50,Baz Luhrmann,490.0,144.812796,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362912,753.0,English,105.0,2013.0,7.3,115000,39.812796,Drama,Romance
2757,Baz Luhrmann,106.0,46.338728,Drama|Romance,Leonardo DiCaprio,Romeo + Juliet,167750,506.0,English,14.5,1996.0,6.8,10000,31.838728,Drama,Romance
1422,Randall Wallace,83.0,56.876365,Action|Adventure,Leonardo DiCaprio,The Man in the Iron Mask,125219,244.0,English,35.0,1998.0,6.4,0,21.876365,Action,Adventure
308,Martin Scorsese,606.0,116.866727,Biography|Comedy|Crime|Drama,Leonardo DiCaprio,The Wolf of Wall Street,780588,1138.0,English,100.0,2013.0,8.2,138000,16.866727,Biography,Comedy
1453,Clint Eastwood,392.0,37.304950,Biography|Crime|Drama,Leonardo DiCaprio,J. Edgar,102728,279.0,English,35.0,2011.0,6.6,16000,2.304950,Biography,Crime
257,Martin Scorsese,267.0,102.608827,Biography|Drama,Leonardo DiCaprio,The Aviator,264318,799.0,English,110.0,2004.0,7.5,0,-7.391173,Biography,Drama
2067,Jerry Zaks,45.0,12.782508,Drama,Leonardo DiCaprio,Marvin's Room,20163,71.0,English,23.0,1996.0,6.7,1000,-10.217492,Drama,Drama
990,Danny Boyle,118.0,39.778599,Adventure|Drama|Thriller,Leonardo DiCaprio,The Beach,176169,548.0,English,50.0,2000.0,6.6,0,-10.221401,Adventure,Drama
1114,Sam Mendes,323.0,22.877808,Drama|Romance,Leonardo DiCaprio,Revolutionary Road,152591,414.0,English,35.0,2008.0,7.3,0,-12.122192,Drama,Romance
1560,Sam Raimi,63.0,18.636537,Action|Thriller|Western,Leonardo DiCaprio,The Quick and the Dead,69197,216.0,English,32.0,1995.0,6.4,0,-13.363463,Action,Thriller
326,Martin Scorsese,233.0,77.679638,Crime|Drama,Leonardo DiCaprio,Gangs of New York,314033,1166.0,English,100.0,2002.0,7.5,0,-22.320362,Crime,Drama
641,Ridley Scott,238.0,39.380442,Action|Drama|Thriller,Leonardo DiCaprio,Body of Lies,174248,263.0,English,70.0,2008.0,7.1,0,-30.619558,Action,Drama
307,Edward Zwick,166.0,57.366262,Adventure|Drama|Thriller,Leonardo DiCaprio,Blood Diamond,400292,657.0,English,100.0,2006.0,8.0,14000,-42.633738,Adventure,Drama
400,Steven Soderbergh,186.0,183.405771,Crime|Thriller,Brad Pitt,Ocean's Eleven,402645,845.0,English,85.0,2001.0,7.8,0,98.405771,Crime,Thriller
255,Doug Liman,233.0,186.336103,Action|Comedy|Crime|Romance|Thriller,Brad Pitt,Mr. & Mrs. Smith,348861,798.0,English,120.0,2005.0,6.5,0,66.336103,Action,Comedy
940,Neil Jordan,120.0,105.264608,Drama|Fantasy|Horror,Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406.0,English,60.0,1994.0,7.6,11000,45.264608,Drama,Fantasy
470,David Ayer,406.0,85.707116,Action|Drama|War,Brad Pitt,Fury,303185,701.0,English,68.0,2014.0,7.6,82000,17.707116,Action,Drama
254,Steven Soderbergh,198.0,125.531634,Crime|Thriller,Brad Pitt,Ocean's Twelve,284852,627.0,English,110.0,2004.0,6.4,0,15.531634,Crime,Thriller
2204,Alejandro G. Iñárritu,285.0,34.300771,Drama,Brad Pitt,Babel,243799,908.0,English,25.0,2006.0,7.5,0,9.300771,Drama,Drama
2682,Andrew Dominik,414.0,14.938570,Crime|Thriller,Brad Pitt,Killing Them Softly,111625,369.0,English,15.0,2012.0,6.2,20000,-0.061430,Crime,Thriller
2898,Tony Scott,122.0,12.281500,Action|Crime|Drama|Romance|Thriller,Brad Pitt,True Romance,163492,460.0,English,13.0,1993.0,8.0,15000,-0.718500,Action,Crime
2333,Angelina Jolie Pitt,131.0,0.531009,Drama|Romance,Brad Pitt,By the Sea,7976,61.0,English,10.0,2015.0,5.3,0,-9.468991,Drama,Romance
1490,Terrence Malick,584.0,13.303319,Drama|Fantasy,Brad Pitt,The Tree of Life,136367,975.0,English,32.0,2011.0,6.7,39000,-18.696681,Drama,Fantasy
101,David Fincher,362.0,127.490802,Drama|Fantasy|Romance,Brad Pitt,The Curious Case of Benjamin Button,459346,822.0,English,150.0,2008.0,7.8,23000,-22.509198,Drama,Fantasy
683,David Fincher,315.0,37.023395,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,63.0,1999.0,8.8,48000,-25.976605,Drama,Drama
1722,Andrew Dominik,273.0,3.904982,Biography|Crime|Drama|History|Western,Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415.0,English,30.0,2007.0,7.5,0,-26.095018,Biography,Crime
611,Jean-Jacques Annaud,76.0,37.901509,Adventure|Biography|Drama|History|War,Brad Pitt,Seven Years in Tibet,96385,119.0,English,70.0,1997.0,7.0,0,-32.098491,Adventure,Biography
792,Patrick Gilmore,98.0,26.288320,Adventure|Animation|Comedy|Drama|Family|Fantas...,Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91.0,English,60.0,2003.0,6.7,880,-33.711680,Adventure,Animation
147,Wolfgang Petersen,220.0,133.228348,Adventure,Brad Pitt,Troy,381672,1694.0,English,175.0,2004.0,7.2,0,-41.771652,Adventure,Adventure
382,Tony Scott,142.0,0.026871,Action|Crime|Thriller,Brad Pitt,Spy Game,121259,361.0,English,92.0,2001.0,7.0,0,-91.973129,Action,Crime

In [40]:
Combined_by_actor = Combined.groupby('actor_1_name')

In [41]:
Combined_by_actor[['num_critic_for_reviews', 'num_user_for_reviews']].mean()

                   num_critic_for_reviews  num_user_for_reviews
actor_1_name
Brad Pitt                      245.000000            742.352941
Leonardo DiCaprio              330.190476            914.476190
Meryl Streep                   181.454545            297.181818

How it works:

actor_1_name == '...' — filters movies where the actor is the lead

pd.concat([...]) — appends all three dataframes row-wise into one

groupby('actor_1_name') — groups by actor

.mean() — calculates mean for both review columns